spring.application.name=OnlineServiceBookingPaymentSystem
spring.datasource.url=jdbc:mysql://localhost:3306/bookingdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

razorpay.key_id=rzp_test_S0GQW4UQNMCLp7
razorpay.key_secret=jbAMQJMNeEg5FwB6S5sTlxVE


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devendrawork078@gmail.com
spring.mail.password=mbcgtzkswoavjktp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.devtools.restart.enabled=false
logging.level.org.springframework=INFO
logging.level.com.devendra=DEBUG